### ISSUE TITLE
为社么编译不通过

### ISSUE THREAD

**Issue by pigsytle** [cheungxiongwei/WMIC#1]
error C2039: "speed": 不是 "WMIC_PhysicalMemory" 的成员
ge : 参见“WMIC_PhysicalMemory”的声明
 error C2039: "speed": 不是 "WMIC_PhysicalMemory" 的成员
ge : 参见“WMIC_PhysicalMemory”的声明
 error C2039: "Processor": 不是 "WMIC" 的成员
age : 参见“WMIC”的声明
 error C2065: “pCtx”: 未声明的标识符
 error C2039: "NetworkAdapter": 不是 "WMIC" 的成员
age : 参见“WMIC”的声明
 error C2065: “pCtx”: 未声明的标识符

**Comment by cheungxiongwei** [comment]
请描述编译环境。
